# Generated by Django 6.0.4 on 2026-05-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_copy',
            field=models.FileField(blank=True, null=True, upload_to='drivers/license_copies/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/profile_photos/'),
        ),
    ]
