# Generated by Django 6.0.4 on 2026-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(max_length=20)),
                ('mileage', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
    ]
