# Generated by Django 6.0.4 on 2026-05-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_expense_date_alter_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/invoices_receipts/'),
        ),
    ]
