# Generated by Django 6.0.4 on 2026-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('from_city', models.CharField(max_length=80)),
                ('to_city', models.CharField(max_length=80)),
                ('pickup_point', models.CharField(max_length=255)),
                ('dropoff_point', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('family', 'Family / 7-Seater'), ('premium', 'Premium')], default='economy', max_length=20)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('luggage_bags', models.PositiveIntegerField(default=0)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('booking_reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City Booking Request',
                'verbose_name_plural': 'City Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
