# Generated by Django 6.0.4 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
