# Generated by Django 6.0.4 on 2026-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_messages', '0002_supportmessage_admin_reply_supportmessage_replied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='issue_attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_messages/issue_attachments/'),
        ),
    ]
